import type { Note, Template } from '@shared'
import { IMPORTANT_TAG_NAME } from '@shared'

const now = new Date()

function isoOffset(days = 0, hours = 0) {
  return new Date(now.getTime() + days * 24 * 60 * 60 * 1000 + hours * 60 * 60 * 1000).toISOString()
}

export function createDefaultTemplates(): Template[] {
  const createdAt = now.toISOString()

  return [
    {
      id: 'tpl-meeting',
      key: 'meeting',
      name: '会议记录',
      description: '适合项目例会、需求评审与周会纪要。',
      icon: 'MessagesSquare',
      createdAt,
      updatedAt: createdAt,
      note: {
        title: '会议记录',
        content: '会议主题：\n参会人员：\n会议结论：\n下一步行动：',
        tags: ['会议', '工作'],
        color: '#f6f3ff',
        completed: false,
        type: 'note',
        checklist: [],
        pinned: false,
        priority: 'normal',
        status: 'todo',
        order: 0,
        dueDate: null,
        remindAt: null,
      },
    },
    {
      id: 'tpl-shopping',
      key: 'shopping',
      name: '购物清单',
      description: '适合采购、囤货与出门前确认。',
      icon: 'ShoppingCart',
      createdAt,
      updatedAt: createdAt,
      note: {
        title: '购物清单',
        content: '',
        tags: ['清单', '生活'],
        color: '#eefbf5',
        completed: false,
        type: 'checklist',
        checklist: [
          {
            id: 'tpl-shopping-1',
            text: '牛奶',
            completed: false,
            order: 0,
            createdAt,
            updatedAt: createdAt,
          },
          {
            id: 'tpl-shopping-2',
            text: '鸡蛋',
            completed: false,
            order: 1,
            createdAt,
            updatedAt: createdAt,
          },
        ],
        pinned: false,
        priority: 'normal',
        status: 'todo',
        order: 0,
        dueDate: null,
        remindAt: null,
      },
    },
    {
      id: 'tpl-study',
      key: 'study',
      name: '学习计划',
      description: '适合课程拆解、知识点回顾和练习安排。',
      icon: 'NotebookPen',
      createdAt,
      updatedAt: createdAt,
      note: {
        title: '学习计划',
        content: '本周目标：\n关键资料：\n复盘笔记：',
        tags: ['学习', '计划'],
        color: '#eef5ff',
        completed: false,
        type: 'note',
        checklist: [],
        pinned: false,
        priority: 'normal',
        status: 'todo',
        order: 0,
        dueDate: null,
        remindAt: null,
      },
    },
    {
      id: 'tpl-retro',
      key: 'retro',
      name: '项目复盘',
      description: '适合阶段总结、风险清单和行动闭环。',
      icon: 'ChartColumnIncreasing',
      createdAt,
      updatedAt: createdAt,
      note: {
        title: '项目复盘',
        content: '做得好的：\n需要改进的：\n风险与阻塞：\n下一轮动作：',
        tags: ['复盘', '项目'],
        color: '#fff5ef',
        completed: false,
        type: 'note',
        checklist: [],
        pinned: false,
        priority: 'high',
        status: 'todo',
        order: 0,
        dueDate: null,
        remindAt: null,
      },
    },
  ]
}

export function createSampleNotes(): Note[] {
  return [
    {
      id: 'sample-launch',
      title: '产品发布前检查',
      content: '把最后一轮体验问题收口，并确认导出与回收站流程都已跑通。',
      tags: ['工作', '发布', IMPORTANT_TAG_NAME],
      color: '#fff3f3',
      completed: false,
      type: 'checklist',
      checklist: [
        {
          id: 'sample-launch-1',
          text: '验证 PWA 安装流程',
          completed: true,
          order: 0,
          createdAt: isoOffset(-2),
          updatedAt: isoOffset(-1),
        },
        {
          id: 'sample-launch-2',
          text: '走通 JSON / Markdown / TXT 导出',
          completed: false,
          order: 1,
          createdAt: isoOffset(-2),
          updatedAt: isoOffset(-1),
        },
        {
          id: 'sample-launch-3',
          text: '确认回收站恢复与永久删除',
          completed: false,
          order: 2,
          createdAt: isoOffset(-2),
          updatedAt: isoOffset(-1),
        },
      ],
      pinned: true,
      priority: 'high',
      status: 'doing',
      order: 0,
      dueDate: isoOffset(1),
      remindAt: isoOffset(0, 1),
      deletedAt: null,
      archivedAt: null,
      createdAt: isoOffset(-3),
      updatedAt: isoOffset(-1),
      completedAt: null,
      source: 'template',
      version: 1,
      syncStatus: 'local',
    },
    {
      id: 'sample-dashboard',
      title: '周会纪要整理',
      content: '整理今天的项目周会纪要，把决议同步给设计和开发。',
      tags: ['会议', '工作'],
      color: '#f6f3ff',
      completed: false,
      type: 'note',
      checklist: [],
      pinned: false,
      priority: 'normal',
      status: 'todo',
      order: 1,
      dueDate: isoOffset(0, 8),
      remindAt: isoOffset(0, 2),
      deletedAt: null,
      archivedAt: null,
      createdAt: isoOffset(-1),
      updatedAt: isoOffset(-1),
      completedAt: null,
      source: 'local',
      version: 1,
      syncStatus: 'local',
    },
    {
      id: 'sample-reading',
      title: '设计心理学读书笔记',
      content: '补充第五章里的可见性与反馈原则，并整理成对外分享稿。',
      tags: ['学习', '设计'],
      color: '#eef5ff',
      completed: false,
      type: 'note',
      checklist: [],
      pinned: false,
      priority: 'low',
      status: 'todo',
      order: 2,
      dueDate: isoOffset(4),
      remindAt: null,
      deletedAt: null,
      archivedAt: null,
      createdAt: isoOffset(-5),
      updatedAt: isoOffset(-3),
      completedAt: null,
      source: 'local',
      version: 1,
      syncStatus: 'local',
    },
    {
      id: 'sample-retro',
      title: '项目复盘草稿',
      content: '从交付节奏、接口稳定性、设计协作三个方向收集复盘要点。',
      tags: ['项目', '复盘', IMPORTANT_TAG_NAME],
      color: '#fff5ef',
      completed: false,
      type: 'note',
      checklist: [],
      pinned: false,
      priority: 'high',
      status: 'doing',
      order: 3,
      dueDate: isoOffset(-1),
      remindAt: isoOffset(-1),
      deletedAt: null,
      archivedAt: null,
      createdAt: isoOffset(-6),
      updatedAt: isoOffset(-1),
      completedAt: null,
      source: 'local',
      version: 1,
      syncStatus: 'dirty',
    },
    {
      id: 'sample-family',
      title: '周末家庭采购',
      content: '',
      tags: ['生活', '清单'],
      color: '#eefbf5',
      completed: false,
      type: 'checklist',
      checklist: [
        {
          id: 'sample-family-1',
          text: '火锅底料',
          completed: true,
          order: 0,
          createdAt: isoOffset(-1),
          updatedAt: isoOffset(-1),
        },
        {
          id: 'sample-family-2',
          text: '蔬菜和丸子',
          completed: false,
          order: 1,
          createdAt: isoOffset(-1),
          updatedAt: isoOffset(-1),
        },
      ],
      pinned: false,
      priority: 'normal',
      status: 'todo',
      order: 4,
      dueDate: isoOffset(2),
      remindAt: null,
      deletedAt: null,
      archivedAt: null,
      createdAt: isoOffset(-2),
      updatedAt: isoOffset(-1),
      completedAt: null,
      source: 'local',
      version: 1,
      syncStatus: 'local',
    },
    {
      id: 'sample-archive',
      title: '已归档：12 月学习计划',
      content: 'React Hooks、GraphQL 基础、作品集准备。',
      tags: ['学习', '归档'],
      color: '#f7f9fc',
      completed: true,
      type: 'note',
      checklist: [],
      pinned: false,
      priority: 'normal',
      status: 'done',
      order: 5,
      dueDate: isoOffset(-10),
      remindAt: null,
      deletedAt: null,
      archivedAt: isoOffset(-7),
      createdAt: isoOffset(-18),
      updatedAt: isoOffset(-7),
      completedAt: isoOffset(-8),
      source: 'local',
      version: 1,
      syncStatus: 'synced',
    },
  ]
}
